# -*- coding: utf-8 -*-
"""FishClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11IsqJ9oMgi13pQQOGSiDWv_qnCi-2c8-
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf 
import os
from random import shuffle

# Loading data and navigating to proper directory
from google.colab import drive
drive.mount('/content/drive')
# %cd drive/MyDrive

"""1. Loading Data and Preprocessing"""

# 20% Validation Set, 80% Training Set
train_generator = tf.keras.preprocessing.image.ImageDataGenerator(
    preprocessing_function=tf.keras.applications.mobilenet_v2.preprocess_input,
    validation_split=0.2 
)

test_generator = tf.keras.preprocessing.image.ImageDataGenerator(
    preprocessing_function=tf.keras.applications.mobilenet_v2.preprocess_input
)

train_images = train_generator.flow_from_directory(
    directory= 'DataLoadTest',
    target_size=(224, 224),
    color_mode='rgb',
    class_mode='categorical',
    batch_size=32,
    shuffle=True,
    seed=42,
    subset='training'
)

val_images = train_generator.flow_from_directory(
    directory= 'DataLoadTest',
    target_size=(224, 224),
    color_mode='rgb',
    class_mode='categorical',
    batch_size=32,
    shuffle=True,
    seed=42,
    subset='validation' # Will only take 20% of the total data as the validation data
)

# test_images = test_generator.flow_from_directory(
#     directory= 'Actual Test Dir',
#     target_size=(224, 224),
#     color_mode='rgb',
#     class_mode='categorical',
#     batch_size=32,
#     shuffle=True # I wonder why this was originally set to false
# )

print("Training image shape:", train_images.image_shape)
print("Validation image shape:", train_images.image_shape)

train_images.class_indices

val_images.class_indices

train_images.filenames

